### ISSUE TITLE
very cool! but cant really understand how it works ;-)

### ISSUE THREAD

**Issue by zeltak** [alphapapa/org-recent-headings#2]
Hi again

thx alot again for another awesome package..your trying to compete with abo-abo as the most prolific org package developer? ;-)

yet i still cant get to understand how this works. i jumped to various headers using keyboard, isearch, worf and agenda TAB (that opens the file/header) yet when i issue either the ivy or helm `org-recent-headings` command i get a single header each time (same one)

what am i missing?

thx alot again!

Z

**Comment by alphapapa** [comment]
Hey Z!

Haha, abo-abo is in another league compared to me!  He's a master.

The way this package works is, whenever a function listed in `org-recent-headings-advise-functions` is called, the heading the point is at after running the function is added to the recent headings list.  I've added a bunch of functions to the default list, but isearch and worf are not among them.  That's why you can customize that list of functions, because some people may have other packages that should be put in the list, or just different preferences.  For me, I don't think I want isearch to cause headings to be added to the list (although I might give it a try), but some users might.  So all you have to do is customize that option and add the isearch commands to the list.

Of course, you have to run `org-recent-headings-mode` to activate the functionality.  I assume you did that, because you said you did get a heading in the list.

Now I did add `org-agenda-goto` and `org-agenda-show` and `org-agenda-show-mouse` to the advise-functions list, so pressing TAB in the Agenda should add the heading to the recent list (assuming you have TAB in the Agenda bound to one of those three commands).  If this isn't working for you, let me know and we'll try to fix it.

I should probably improve the docs a bit here.  I think this package has a lot of potential, but I haven't gotten any feedback on it from other users--until now!  :)

Thanks.

**Comment by zeltak** [comment]
thx again, yeah i guess i needed to reactivate ``org-recent-headings-mode``, now it seems to populate the list reliably.
I agree that the package has alot of potential, its very cool!
i did try to add worf to the list like this

```

(setq org-recent-headings-advise-functions '(org-agenda-goto
                                                  org-agenda-show
                                                  org-agenda-show-mouse
                                                  org-show-entry
                                                  org-reveal
                                                  org-refile
                                                  org-tree-to-indirect-buffer
                                                  worf-goto
                                                  helm-org-parent-headings
                                                  helm-org-in-buffer-headings
                                                  helm-org-agenda-files-headings
                                                  org-bookmark-jump
                                                  helm-org-bookmark-jump-indirect))
```

is that the correct way to do so since it didnt really seem to work?

best

Z

**Comment by alphapapa** [comment]
Great!  :)

Yeah, you can do that, although it's easier to use the customize UI, i.e. `M-x customize-option RET org-recent-headings-advise-functions RET`.  Whichever you prefer.  :)

After setting that you need to toggle the mode off and on again.  I'll have to fix it so you don't have to do that...

**Comment by zeltak** [comment]
hmm i restarted emacs yet it still dosent track worf-goto. i wonder perhaps the command isnt worg-goto but something else i need to add?

thx!

Z

**Comment by alphapapa** [comment]
Hmm, I just tested it and it worked for me.  Did you forget to turn `org-recent-headings-mode` off and on again after setting `org-recent-headings-advise-functions`?  (Or just set the variable before turning it on.)

**Comment by zeltak** [comment]
ahh yeah i thought a restart of emacs should do. so i need to manually issue `org-recent-headings-mode` after each restart of emacs ?

this is my current conf

```
(use-package org-recent-headings
 :ensure t
 :config
(require 'org-recent-headings)
(org-recent-headings-mode)


(setq org-recent-headings-advise-functions '(org-agenda-goto
                                                  org-agenda-show
                                                  org-agenda-show-mouse
                                                  org-show-entry
                                                  org-reveal
                                                  org-refile
                                                  org-tree-to-indirect-buffer
                                                  worf-goto
                                                  helm-org-parent-headings
                                                  helm-org-in-buffer-headings
                                                  helm-org-agenda-files-headings
                                                  org-bookmark-jump
                                                  helm-org-bookmark-jump-indirect))

 )
```

best

Z

**Comment by alphapapa** [comment]
Just move the `setq` above `org-recent-headings-mode` and it should work.  As it is, you're changing the variable after activating the mode, but you need to activate the mode after changing the variable.

That's another advantage of using the `customize` system instead of manually doing `setq`.  :)

By the way, if I could impose on you for a moment...  I put up this package recently (not on MELPA yet): https://github.com/alphapapa/org-quick-peek  I'd like to get some feedback on it before I submit it to MELPA.  I wonder if you would find it useful, and if you wouldn't mind testing it briefly and letting me know what you think.  :)

**Comment by zeltak** [comment]
ofc! will test it now and report back in a bit :)

also i modified the conf and it sill dosent work until i manually disable and then enable `org-recent-headings-mode` manuly...maybe its my "magic" touch :)

```
(use-package org-recent-headings
 :ensure t
 :config
(require 'org-recent-headings)

(setq org-recent-headings-advise-functions '(org-agenda-goto
                                                  org-agenda-show
                                                  org-agenda-show-mouse
                                                  org-show-entry
                                                  org-reveal
                                                  org-refile
                                                  org-tree-to-indirect-buffer
                                                  worf-goto
                                                  helm-org-parent-headings
                                                  helm-org-in-buffer-headings
                                                  helm-org-agenda-files-headings
                                                  org-bookmark-jump
                                                  helm-org-bookmark-jump-indirect))

;;needs to be set last in the org-recent-headings config 
(org-recent-headings-mode)

)

```

z

**Comment by alphapapa** [comment]
Hm, I'm not sure why that would be.  I guess I would suggest restarting Emacs one more time.

BTW, if you really don't want to use `customize` for that, you can add a function to it like this:

`(push 'worf-goto org-recent-headings-advise-functions)`

...instead of having to specify the entire list.  :)

**Comment by zeltak** [comment]
ok i tried org-quick-peek and i get an error (assuming i did it correctly :))

So this is what i did
installed quick-peek
evaled `org-quick-peek`
M-x `org-quick-peek-mode`

then copied a link from one org file (A) and added an org link to another file (B)
then in file B while point is on the org-link i issues `org-quick-peek-link`

and got this error:

```setq: Symbol’s function definition is void: org-extract-attributes```

best

Z

**Comment by alphapapa** [comment]
Thank you very much, this was my mistake, because I copied code from `org.el`, but I hadn't yet upgraded to Org 9, so it was calling a function that doesn't exist in Org 9.  I fixed it, so `org-quick-peek-link` should work now.

And as far as I know, the agenda-peeking commands do work...

**Comment by zeltak** [comment]
awesome, the peep-link now works..pretty cool :)

i also tried the peek-agenda commands but they dont seem to do anything and i also get no error?

also i cant get the worf thing to load as default unless i disable/enable the mode

this is as you suggested my current conf

```
(use-package org-recent-headings
 :ensure t
 :config
(require 'org-recent-headings)
(push 'worf-goto org-recent-headings-advise-functions)
;; ;;needs to be set last in the org-recent-headings config 
(org-recent-headings-mode)

)

**Comment by alphapapa** [comment]
Thanks for your feedback on the agenda peeking.  I just pushed a commit that removes all the key-binding customization, which wasn't working, so users can bind their own keys for now.  The agenda-peeking commands should work, but please let me know if they aren't working for you.

I'm sorry, I don't know why the code you posted isn't working.  At some point I will add a setter for the functions list that should generally take care of that, but as far as I know, the code you posted should work.  I'd suggest using the customization interface for setting the functions list, because it seems to work for me.

Thanks for all your help.

**Comment by alphapapa** [comment]
FYI, I just fixed a bug that may have rendered the `--store-heading` function completely inoperative and prevented any headings from being stored in the recent list.  This may have been the problem you were encountering.  If so, I'm sorry for sending you in circles like this.  If you're still interested in using this package, please let me know if it works for you now.  :)

**Comment by zeltak** [comment]
cool no worries man, im always happy to help test and find bugs, i really enjoy all your emacs packages :)

is it pushed to melpa yet? ill try after work today and report back!

best 

Z

**Comment by alphapapa** [comment]
I pushed it but I doubt MELPA has built it yet.  Probably in 2-3 hours it should be.  Thanks!

**Comment by zeltak** [comment]
closing, its working amazingly well for past week or so..another super cool package from the "@alphapapa-verse"

thx!!!

Z

**Comment by alphapapa** [comment]
Great!  Thanks.  :)
